USE flexistore;
SHOW TABLES;
SELECT '======= USERS =======';
SELECT id, name, username, role, created_at FROM users;
SELECT '======= CLIENTS =======';
SELECT id, name, phone, total_debt, created_at FROM clients;
SELECT '======= PRODUCTS =======';
SELECT id, barcode, name, selling_price, stock_quantity, status FROM products;
SELECT '======= INVOICES =======';
SELECT id, client_id, user_id, total_amount, payment_type, created_at FROM invoices;
SELECT '======= INVOICE_ITEMS =======';
SELECT * FROM invoice_items;
SELECT '======= INSTALLMENTS =======';
SELECT id, client_id, invoice_id, total_amount, remaining_amount, months, monthly_installment, status FROM installments;
SELECT '======= INSTALLMENT_PAYMENTS =======';
SELECT id, installment_id, user_id, amount_paid, payment_date FROM installment_payments;
SELECT '======= TRANSACTION_LOGS =======';
SELECT id, user_id, action_type, amount, created_at FROM transaction_logs;
SELECT '======= INVENTORY_LOGS =======';
SELECT id, product_id, user_id, action_type, quantity_changed, created_at FROM inventory_logs;
